common_dir: data
dataset:
  file_name: dataset.csv

loader:
  type: csv
  csv_loader:
    link: http://dl.dropboxusercontent.com/s/wzos2plf8lstwes/data.csv?dl=0

trainer:
  model:
    max_df: 0.8
    min_count: 5
    max_iter: 10000
    model_file: pipe.zip
