apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-{{ include "ppw-chart.fullname" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "ppw-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ppw-chart.fullname" . }}
    spec:
      volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          claimName: {{ include "ppw-chart.fullname" . }}
      containers:
      - name: {{ include "ppw-chart.fullname" . }}
        image: {{ .Values.image.repository }}/results_server
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - mountPath: {{ .Values.volume.mountPath }}
          name: {{ .Values.volume.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-{{ include "ppw-chart.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ppw-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ppw-chart.fullname" . }}
    spec:
      volumes:
      - name: {{ .Values.volume.name }}
        persistentVolumeClaim:
          claimName: {{ include "ppw-chart.fullname" . }}
      containers:
      - name: {{ include "ppw-chart.fullname" . }}
        image: {{ .Values.image.repository }}/pravega-w
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: {{ .Values.volume.mountPath }}
          name: {{ .Values.volume.name }}

