apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ppw-chart.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.claim.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.claim.storage }}
