apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ppw-chart.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 3Gi
