apiVersion: v1
kind: Service
metadata:
  name: {{ include "ppw-chart.fullname" . }}
  labels:
    app: {{ include "ppw-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ include "ppw-chart.fullname" . }}

