apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppw-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ppw-processor
  template:
    metadata:
      labels:
        app: ppw-processor
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-claim
      containers:
      - name: ppw-processor
        image: dxd360/ppw-processor
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: data-volume
