apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppw-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ppw-server
  template:
    metadata:
      labels:
        app: ppw-server
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-claim
      containers:
      - name: ppw-server
        image: dxd360/ppw-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 666
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: data-volume
