apiVersion: v1
kind: Service
metadata:
  name: cats-server
  labels:
    app: cats-server
spec:
  type: NodePort
  ports:
  - port: 666
    targetPort: 666
    protocol: TCP
    name: http
  selector:
    app: cats-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cats-server
  template:
    metadata:
      labels:
        app: cats-server
    spec:
      volumes:
      - name: results-volume
        persistentVolumeClaim:
          claimName: results-claim
      containers:
      - name: cats-server
        image: dxd360/results_server
        imagePullPolicy: Always
        ports:
        - containerPort: 666
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: results-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pravega-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pravega-writer
  template:
    metadata:
      labels:
        app: pravega-writer
    spec:
      volumes:
      - name: results-volume
        persistentVolumeClaim:
          claimName: results-claim
      containers:
      - name: pravega-writer
        image: dxd360/pravega-w
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: results-volume

