
nameOverride: ""
fullnameOverride: ""

# Service for deployments
service:
  type: NodePort
  port: 666

# Repository of images and pullPolicy
image:
  repository: dxd360
  pullPolicy: Always

volume:
  mountPath: /usr/src/app/data
  name: results-volume
