void setBuildStatus(String message, String state) {
  step([
      $class: "GitHubCommitStatusSetter",
      reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/safronovD/python-pravega-writer"],
      contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "Robot tests"],
      errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
      statusResultSource: [ $class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
  ]);
}
pipeline {
   agent any
   // options {
   //      timestamps()
   //      }
   stages {
       stage('Deploy') {
            steps {
                  sh 'echo Deploy'  
            //     sh 'pip install -r Connector/requirements.txt'
            //     sh 'pip install -r Server/requirements.txt'
            //     sh 'pip install -r Tests/requirements.txt'
            // }
        }
      }
    
    }
    post { 
          success {
            setBuildStatus("Deploy succeeded", "SUCCESS");
          }
          failure {
            setBuildStatus("Deploy failed", "FAILURE");
          }
         
	  }
}