apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
spec:
  containers:
  - name: python
    image: python:3.7
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
  - name: docker
    image: docker:19.03
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    volumeMounts:
     - name: docker
       mountPath: /var/run/docker.sock
  volumes:
  - name: docker
    hostPath:
    path: /var/run/docker.sock