name: Trigger

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Jenkins trigger
      run: |
        curl -I -u ${{ secrets.jenkins_user }}:${{ secrets.jenkins_token }} ${{ secrets.jenkins_url }}/job/Main/build?token=${{ secrets.jenkins_token }}