name: Unit tests

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    needs: Python linting
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/connector/requirements.txt
        pip install -r ./src/server/requirements.txt
        pip install -r ./src/ml-controller/requirements.txt

        pip install -r ./src/connector/test/requirements.txt
        pip install -r ./src/server/test/requirements.txt
        pip install -r ./src/ml-controller/test/requirements.txt

        mkdir -p reports/connector
        mkdir -p reports/ml-controller
        mkdir -p reports/server


    - name: Connector unit tests
      run: |
        python3 -m robot.run  --outputdir reports/connector ./src/connector/test/unit.robot


    - name: ML-controller unit tests
      run: |
        python3 -m robot.run  --outputdir reports/ml-controller ./src/ml-controller/test/unit.robot

    - name: Server unit tests
      run: |
        python3 -m robot.run  --outputdir reports/server ./src/server/test/unit.robot
